### ISSUE TITLE
Problem with pagination

### ISSUE THREAD

**Issue by LuciaCL** [GraffiTab/GraffiTab-iOS#14]
Problem in "Near me" , "Trending"  and "Recent" pages, I think that the pagination should stop and not put again form the beginning when you scroll back. I am not sure, if you do this on purpose or not.

**Comment by 8masterofpuppets8** [comment]
So the pagination should be scrolling endlessly - you scroll to the bottom, it loads more. Then when you scroll to the top it shows the newest things. It should be fine :)
