### ISSUE TITLE
Problem loading pictures list form camera roll

### ISSUE THREAD

**Issue by LuciaCL** [GraffiTab/GraffiTab-iOS#6]
I try to upload a photo from my gallery, but i cant see the thumbnails.I have screenshoot, but i cant upload here.

**Comment by LuciaCL** [comment]
![image](https://cloud.githubusercontent.com/assets/15170715/15840026/fe326c56-2c3e-11e6-942a-a3a8b62cba22.png)
![image](https://cloud.githubusercontent.com/assets/15170715/15840027/fe3772f0-2c3e-11e6-9bd0-af9c2510e311.png)

**Comment by 8masterofpuppets8** [comment]
WIll be fixed when native iPad layout is introduced.
